channels:
- defaults
- conda-forge
- anaconda
dependencies:
- conda:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _pytorch_select=1.0
  - _tensorflow_select=1.0
  - abseil-cpp=20210324.2
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=8.0.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.4.0
  - autovizwidget=0.20.0
  - av=9.2.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - black=22.6.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.0
  - bokeh=2.4.3
  - boto3=1.24.28
  - botocore=1.27.28
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.1.0
  - cryptography=39.0.1
  - cx_oracle=8.3.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - dm-tree=0.1.5
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.2.2
  - flatbuffers=2.0.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freeglut=3.0.0
  - freetds=1.3.3
  - freetype=2.12.1
  - frozenlist=1.2.0
  - fsspec=2021.10.1
  - future=0.18.3
  - gast=0.4.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - googleapis-common-protos=1.56.4
  - graphite2=1.3.14
  - greenlet=1.1.1
  - grpc-cpp=1.41.0
  - grpcio=1.42.0
  - h5py=3.6.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - hdijupyterutils=0.20.0
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - importlib-metadata=4.11.3
  - iniconfig=1.1.1
  - ipykernel=6.9.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jasper=2.0.14
  - jedi=0.18.1
  - jinja2=3.0.3
  - jmespath=0.10.0
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter_client=7.3.5
  - jupyter_core=4.11.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keras=2.9.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - leveldb=1.20
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.84.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglu=9.0.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - liblightgbm=3.3.2
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnghttp2=1.46.0
  - libopenblas=0.3.20
  - libopencv=4.6.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.19.6
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libthrift=0.15.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libutf8proc=2.6.1
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxgboost=1.6.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - lightgbm=3.3.2
  - llvm-openmp=14.0.6
  - llvmlite=0.39.0
  - lmdb=0.9.29
  - locket=1.0.0
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markdown=3.3.4
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mock=4.0.3
  - mpi=1.0
  - multidict=5.2.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.8.4
  - nose=1.3.7
  - notebook=6.4.12
  - numactl=2.0.12
  - numba=0.56.1
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - oauthlib=3.2.1
  - onnx=1.12.0
  - onnxconverter-common=1.9.0
  - opencv=4.6.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openmpi=4.1.1
  - openpyxl=3.0.10
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - orc=1.7.4
  - packaging=21.3
  - pandas=1.4.3
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.9.0
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.1.2
  - pixman=0.40.0
  - platformdirs=2.5.2
  - plotly=5.9.0
  - pluggy=1.0.0
  - portpicker=1.3.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - protobuf=3.19.6
  - psutil=5.9.0
  - psycopg2=2.8.6
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py-opencv=4.6.0
  - pyarrow=8.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pycryptodomex=3.15.0
  - pydeprecate=0.3.2
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pymssql=2.2.5
  - pyodbc=4.0.34
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pyspnego=0.3.1
  - pytest=7.1.2
  - python=3.10.9
  - python-clang=14.0.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - pytorch-base=1.12.1
  - pytorch-cpu=1.12.1
  - pytorch-lightning=1.6.5
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - re2=2022.04.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-kerberos=0.14.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.6
  - s3transfer=0.6.0
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - sentencepiece=0.1.96
  - setuptools=65.6.3
  - six=1.16.0
  - skl2onnx=1.12
  - snapml=1.8.12
  - snappy=1.1.9
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sparkmagic=0.20.0
  - sqlalchemy=1.4.39
  - sqlite=3.40.1
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tabulate=0.8.10
  - tbb=2021.5.0
  - tenacity=8.0.1
  - tensorboard=2.9.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow-addons=0.17.0
  - tensorflow-base=2.9.3
  - tensorflow-cpu=2.9.3
  - tensorflow-estimator=2.9.0
  - tensorflow-hub=0.12.0
  - tensorflow-io-gcs-filesystem=0.26.0
  - tensorflow-metadata=1.8.0
  - tensorflow-model-optimization=0.7.3
  - tensorflow-probability=0.17.0
  - tensorflow-text=2.9.0
  - termcolor=1.1.0
  - terminado=0.13.1
  - tf2onnx=1.12.1
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.11.2
  - torchmetrics=0.8.1
  - torchtext-base=0.13.1
  - torchvision-base=0.13.1
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typeguard=2.12.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - unixodbc=2.3.11
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - werkzeug=2.2.2
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - wrapt=1.14.1
  - x264=1!157.20191217
  - xgboost=1.6.2
  - xlrd=2.0.1
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.4.9
- pip:
  - assetframe-lib==0.1.5
  - autoai-libs==1.14.9
  - autoai-ts-libs==2.0.6
  - azure-core==1.25.0
  - azure-cosmos==4.3.0
  - ca-data-connector==11.2.4.220902122555
  - cassandra-driver==3.25.0
  - cplex==22.1.0.0
  - decision-optimization-client==1.0.1
  - dill==0.3.5.1
  - docplex==2.23.222
  - gensim==4.1.2
  - geomet==0.2.1.post1
  - greenery==3.3.3
  - hyperopt==0.2.5
  - ibm-cloud-sdk-core==3.10.1
  - ibm-cos-sdk==2.12.0
  - ibm-cos-sdk-core==2.12.0
  - ibm-cos-sdk-s3transfer==2.12.0
  - ibm-data-fabric-sdk==0.0.7
  - ibm-db==3.1.3
  - ibm-db-sa==0.3.8
  - ibm-watson-machine-learning==1.0.288
  - ibm-watson-openscale==3.0.28
  - ibm-watson-studio-lib==3.0.12
  - itc-utils==0.1.15
  - jaydebeapi==1.2.3
  - jpype1==1.4.0
  - jsonref==0.2
  - jsonsubschema==0.0.6
  - lale==0.7.1
  - lomond==0.3.3
  - mlxtend==0.20.0
  - mysql-connector-python==8.0.32
  - portion==2.3.0
  - project-lib==2.0.7
  - py4j==0.10.9.7
  - python-graphviz==0.20.1
  - simplejson==3.17.6
  - smart-open==6.1.0
name: wml_runtime-22.2-py3.10
