site_name: Mlflow-WatsonML
theme:
  name: material
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [mlflow_watsonml] # search packages in the src folder
          options:
            docstring_style: numpy
